name: Create Issue From pytest log
description: >-
  Create an issue for failed tests from a pytest-reportlog file.
inputs:
  log-path:
    description: >-
      The path to the log file
    required: true
  issue-title:
    description: >-
      Title of issue being created or updated. Can be a parametrized string, in which case
      a new issue will be opened for all variations.
    required: false
    default: "⚠️ Nightly upstream-dev CI failed ⚠️"
  issue-label:
    description: >-
      Labels to apply to issue
    required: false
    default: "CI"
  assignees:
    description: >-
      Comma-separated users to assign to the issue (no spaces). All assigned users have to
      have commit rights.
    required: false
    default: ""
outputs: {}
branding:
  color: "red"
  icon: "alert-triangle"

runs:
  using: composite
  steps:
    - name: print environment information
      shell: bash -l {0}
      run: |
        python --version
        python -m pip list
    - name: install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install pytest more-itertools
    - name: produce the issue body
      shell: bash -l {0}
      env:
        LOG_PATH: ${{ inputs.log-path }}
        WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        ISSUE_BODY: ${{ github.action_path }}/issue-body.md
      run: |
        python $GITHUB_ACTION_PATH/parse_logs.py "$LOG_PATH" "$WORKFLOW_URL" "$ISSUE_BODY"
    - name: inspect the issue body
      shell: bash
      env:
        LOG_PATH: ${{ inputs.log-path }}
        ISSUE_BODY: ${{ github.action_path }}/issue-body.md
      run: |
        # raw log file
        echo "::group::reportlog file"
        jq -M "$LOG_PATH"
        echo "::endgroup::"

        # issue body
        echo "::group::issue body"
        cat "$ISSUE_BODY"
        echo "::endgroup::"

    - name: create the issue
      shell: bash
      env:
        ASSIGNEES: ${{ inputs.assignees }}
        ISSUE_TITLE: ${{ inputs.issue-title }}
        ISSUE_LABEL: ${{ inputs.issue-label }}
        CREATOR: "app/github-actions"
        GH_TOKEN: ${{ github.token }}
      run: |
        issues=$(
          gh issue list \
            -S "in:title $ISSUE_TITLE" \
            --state open \
            --author $CREATOR \
            --json number,title,author,assignees \
            -L 1
        );

        if [[ $(echo "$issues" | jq 'length') -eq 1 ]]; then
            gh issue edit \
              "$(echo "$issues" | jq '.[] | .number')" \
              --body-file $GITHUB_ACTION_PATH/issue_body.md
        else
            gh issue new \
              --assignee "$ASSIGNEES" \
              --label "$ISSUE_LABEL" \
              --title "$ISSUE_TITLE" \
              --body-file $GITHUB_ACTION_PATH/issue_body.md
        fi
